# Generated by Django 4.2.11 on 2025-09-04 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredPersons',
            fields=[
                ('insured_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_of_birth', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsurerEmployees',
            fields=[
                ('insurer_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsurenceQuestionare',
            fields=[
                ('insurence_questionare_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('question_1_answer', models.IntegerField(default=0)),
                ('question_2_answer', models.IntegerField(default=0)),
                ('question_3_answer', models.IntegerField(default=0)),
                ('question_4_answer', models.IntegerField(default=0)),
                ('question_5_answer', models.IntegerField(default=0)),
                ('question_6_answer', models.IntegerField(default=0)),
                ('question_7_answer', models.IntegerField(default=0)),
                ('question_8_answer', models.IntegerField(default=0)),
                ('question_9_answer', models.IntegerField(default=0)),
                ('question_10_answer', models.IntegerField(default=0)),
                ('insured_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_person', to='Insurence_Web.insuredpersons')),
                ('insurer_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurer_employee', to='Insurence_Web.insuredpersons')),
            ],
        ),
        migrations.CreateModel(
            name='Insurence',
            fields=[
                ('insurence_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('insurence_start', models.DateTimeField()),
                ('insurence_end', models.DateTimeField()),
                ('insurence_type', models.CharField(max_length=100)),
                ('insurence_monthly_payment', models.PositiveIntegerField()),
                ('insurence_loss_payment', models.PositiveIntegerField()),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insurence_Web.insuredpersons')),
                ('insurence_questionare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insurence_Web.insurencequestionare')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Insurence_Web.insureremployees')),
            ],
        ),
        migrations.AddField(
            model_name='insuredpersons',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Insurence_Web.insureremployees'),
        ),
    ]
