# Generated by Django 4.2.11 on 2025-09-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurence_Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurence',
            old_name='insurence_loss_payment',
            new_name='insurence_claims_payment',
        ),
        migrations.RenameField(
            model_name='insurencequestionare',
            old_name='insured_fk',
            new_name='insured',
        ),
        migrations.RenameField(
            model_name='insurencequestionare',
            old_name='insurer_fk',
            new_name='insurer',
        ),
    ]
