# Generated by Django 4.2.11 on 2025-09-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurence_Web', '0002_rename_insurence_loss_payment_insurence_insurence_claims_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuredpersons',
            name='insurer',
        ),
        migrations.AlterField(
            model_name='insuredpersons',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insuredpersons',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='insurence',
            name='insurence_claims_payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insurence',
            name='insurence_monthly_payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insurencequestionare',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurer_employee', to='Insurence_Web.insuredpersons'),
        ),
    ]
