# Generated by Django 4.2.11 on 2025-09-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurence_Web', '0003_remove_insuredpersons_insurer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurencequestionare',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurer_employee', to='Insurence_Web.insureremployees'),
        ),
    ]
