# Generated by Django 4.2.11 on 2025-10-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurence_Web', '0004_alter_insurencequestionare_insurer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuredpersons',
            name='password',
        ),
        migrations.AddField(
            model_name='insuredpersons',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=7),
        ),
        migrations.AddField(
            model_name='insureremployees',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=7),
        ),
        migrations.AlterField(
            model_name='insuredpersons',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='insurencequestionare',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurer_employee', to='Insurence_Web.insureremployees'),
        ),
    ]
