# Generated by Django 6.0.2 on 2026-02-26 17:15

import Insurence_Web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurence_Web', '0005_remove_insuredpersons_password_insuredpersons_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredpersons',
            name='phone_number_prefix',
            field=models.CharField(choices=Insurence_Web.models.get_prefix_choices, default='+421', max_length=4),
        ),
    ]
