# Generated by Django 6.0.2 on 2026-02-27 20:57

import Insurence_Web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurence_Web', '0006_insuredpersons_phone_number_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredpersons',
            name='bank_account_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredpersons',
            name='birth_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredpersons',
            name='city',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredpersons',
            name='goverment_id',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredpersons',
            name='home_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredpersons',
            name='parcel',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredpersons',
            name='post_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuredpersons',
            name='state',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insuredpersons',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='insuredpersons',
            name='phone_number_prefix',
            field=models.CharField(choices=Insurence_Web.models.get_prefix_choices, default='CZ', max_length=4),
        ),
    ]
