# Generated by Django 6.0.2 on 2026-02-27 21:32

import Insurence_Web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurence_Web', '0007_insuredpersons_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureremployees',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insureremployees',
            name='phone_number_prefix',
            field=models.CharField(choices=Insurence_Web.models.get_prefix_choices, default='CZ', max_length=4),
        ),
        migrations.AlterField(
            model_name='insuredpersons',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insureremployees',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
