# Generated by Django 6.0.2 on 2026-05-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurence_Web', '0009_insuredpersons_home_delivery_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredpersons',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=7),
        ),
        migrations.AlterField(
            model_name='insureremployees',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='M', max_length=7),
        ),
    ]
